### PR TITLE
Lsp-clang for standard CMake project layouts

### PR DESCRIPTION
**Pull request by jsalzbergedu**
With compile_commands.json in a build/ directory, it is currently not easy to use lsp-clangd. I don't know if this is the sort of "integration" you want with cmake, but it gets rid of the "using default directory" warnings.

Thanks!

### CODE REVIEW

**Comment by tee3** [comment]
Thank you for your contribution!

I'm in favor of something like this, but I feel this is a bit too CMake related and also seems to assume a layout for CMake projects, which I think is true for many use cases, but not all.

Could this be split into some more general pieces?  Maybe provide variables for the root of the project and the location of the compilation database, then provide cmake-specific functions as in this pull request that set those variables?

What do you think?

**Comment by jsalzbergedu** [comment]
I think that's a great idea.

I may wait to do that until clangd starts working better on my machine (the current build for me gets caught in hangs during trivial use) so that it will be more pleasant to test and use.

**Comment by tee3** [comment]
Thanks @jsalzbergedu, I may take a crack at it at some point as well.  Thanks again!

Which version of clangd are you running?  I run the latest master on macOS and things look pretty good in most instances.

**Comment by jsalzbergedu** [comment]
When I ask Mr. clangd for --version, he tells me

clangd version 8.0.0 (trunk 341258)

**Pull request closed without merging**
